; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_nrf52840_sense]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-mbed-nrf52840-sense
framework = arduino
lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.12.0
    adafruit/Adafruit LSM6DS @ ^4.7.3
    arduino-libraries/ArduinoBLE @ ^1.3.6
build_flags = 
extra_scripts = pre:increment_version.py
